### ISSUE TITLE
Can't enter database. Stuck at "Loading data. Please stand by..."

### ISSUE THREAD

**Issue by dado330** [evilbiscu1t/TentaclesManager#13]
I've already accessed the database multiple times in the past.

The password is correct because otherwise it says "Incorrect password."

The problems started once the avatar images were not imported at all. I've immediately tried to reopen the database but Tentacles Manager started acting odd by displaying "Loading data. Please stand by..."

I've tried to:

- Move the database from the external HDD where it's normally stored to the internal drive on my pc.

- Reinstall Tentacles Manager

- Reboot Windows

- Remove the data folder with the avatar and screenshot inside

None of these seems to have any effect.

Anyway, your project is amazing, thanks

**Comment by evilbiscu1t** [comment]
I am sorry to hear that you have you've encountered this problem. I did some tests trying to reproduce this error myself and unfortunately I was able to that. I am saying that is unfortunate because I was able to do that by damaging the database structure. I never thought that something like that can happen. My theory is that in the middle of saving data to the database something crashed and the database was saved to the disc only partially. But it's only theory and I need to confirm it. I never thought about any logging mechanism so right now app doesn't write any useful error logs. I am going to create a new version of the app that will save some logs (or at least display some useful error message) in case of encountering this error. That way we will know for sure if the issue is with database structure. Also, I am going to create some sort of backup system. The app will keep previous versions of the database so that if anything happens to the database structure it will be easy to restore data from backup.

I will try to make this new version as fast as I can. Once we will know for sure what is the source of the problem we can think how to restore your data. I don't know if you are familiar with programming, but if you are you can try editing *.db files and see what's inside. These files are simple text files that can be edited with any text editor (Notepad++ is a good editor for Windows, but classic Notepad is also ok). Maybe there is just some brackets missing or something and it will be easy to fix.

**Comment by evilbiscu1t** [comment]
Ok, so I've released a new version of the app. I wasn't able to create any logging mechanism to get specific error log for this problem but I think that I have a solution. I am pretty sure that the source of the problem was some write error that occurred in the middle of saving data to the database (something like this shouldn't happen but maybe it has something to do with the external drive - not sure). In this new version there is a special function that should fix any corrupted entries in your database. When you lunch the application on the welcome screen right-click your database and choose "Fix database" option. After that just fallow instructions on the screen.

To make sure that the data will be safe even when some write errors occurred I've added a new function that will make backup of database files every time that database is opened.
